version: "3.8"

services:
  tempo:
    image: grafana/tempo:2.4.0
    container_name: tempo
    ports:
      - "3200:3200"
      - "9095:9095"
      - "4317:4317"
      - "4318:4318"
      - "9411:9411"
      - "14268:14268"
    volumes:
      - ./src/main/java/market/analyses/parkour/config/tempo/tempo.yaml:/etc/tempo.yaml
    command: ["-config.file", "/etc/tempo.yaml"]

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - tempo
    volumes:
      - ./data/grafana:/var/lib/grafana

  victoria-metrics:
    image: victoriametrics/victoria-metrics:latest
    container_name: victoria-metrics
    ports:
      - "8428:8428"
    volumes:
      - ./src/main/java/market/analyses/parkour/config/victoria-metrics/promscrape.yaml:/etc/promscrape.yaml
    command: ["-promscrape.config", "/etc/promscrape.yaml"]

  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"

  app:
    build:
      context: .
      dockerfile: dockerfile
      args:
        JAR_FILE: target/parkour-0.0.1-SNAPSHOT.jar
    container_name: application
    ports:
      - "8080:8080"
    environment:
      - JAVA_OPTS=
      - LOKI=http://loki:3100
    depends_on:
      - tempo
      - victoria-metrics
      - loki
    volumes:
      - /tmp:/tmp