scrape_configs:
  - job_name: parkour
    static_configs:
      - targets:
          - "sersh.keenetic.name:8088/actuator/prometheus"
        labels:
          app: parkour
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance